Deployed on Heroku
coding-blocks/hiring-blocks pull request #25
Opened 2017-06-24 15:49 UTC by bhavyaagg

Solves #24 
Running At : https://whispering-garden-72461.herokuapp.com/signup

2017-06-24 16:42 UTC, championswimmer commented
wouldn't you require to specify the Heroku Database name and port etc ? 
In the db/models.js

2017-06-24 16:43 UTC, bhavyaagg commented
Bhaiya uss vaali mai kardia and secrets.json use kardi vaha. Secrets.json toh yaha nahi daalni. @championswimmer

2017-06-24 16:47 UTC, bhavyaagg commented
Deploy karte vakt secret-sample.json ki jagah secret.json use karli

2017-06-24 19:43 UTC, bhavyaagg commented
@championswimmer Updated the PR with the changes in models.js

2017-06-24 19:58 UTC, championswimmer requested changes

2017-06-24 19:58 UTC, championswimmer commented on server.js
>      console.log("Listening on 4000");
fix same in 2nd line too

2017-06-24 19:58 UTC, championswimmer commented on db/models.js
>  const secret = require('./../secret-sample.json');
require from secrets, not secrets-sample

2017-06-24 19:58 UTC, championswimmer commented on db/models.js
> -const db = new Sequelize(secret.DATABASE, secret.DB_USER, secret.DB_PASSWORD, {
require from secrets, not secrets-sample

2017-06-24 20:02 UTC, bhavyaagg commented
@championswimmer Updated the PR

2017-06-24 20:02 UTC, bhavyaagg commented on db/models.js
>  const secret = require('./../secret-sample.json');
Done

2017-06-24 20:08 UTC, bhavyaagg commented
Done Finally i hope @championswimmer

2017-06-24 20:13 UTC, bhavyaagg commented
Done all the changes

2017-06-24 20:49 UTC, bhavyaagg commented
Please review @championswimmer

2017-06-25 19:03 UTC, bhavyaagg commented
Please review @championswimmer

2017-06-26 12:23 UTC, championswimmer approved these changes

2017-06-26 12:24 UTC, merged